server:
  port: ${PORT:8081}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.37.129.14:3306/kunpeng
    username: tangxin
    password: tangxin
#  type: com.alibaba.druid.pool.DruidDataSource
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  ##xml文件的路径配置
  mapper-locations:  classpath*:mapper/*.xml
#    最好建议个目录 不然其它的 lib 库也会扫描进去

#  classpath:/xxx 和 classpath:xxx是一样的 。
    #.
    #classpath:xxx 和 classpath*:xxx是不一样的，前者表示引入一个，后者表示引入多个。
    #.
    #而且classpath*不仅包含class路径，还包括jar文件中(class路径)进行查找。
  #.
  #classpath:mapper/**/*.xml：查找类路径下mapper包下面所有子包中的所有xml。

logging:
    level:
      root: debug
# 详细日志输出