server:
  port: ${PORT:8081}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp17rs6x3634h47kkdo.mysql.rds.aliyuncs.com:3306/rds_mysql_4180jtd
    username: lab_445104143
    password: 076f690c7326_#@Aa
#  type: com.alibaba.druid.pool.DruidDataSource
